### ISSUE TITLE
DAPLink doesn't work with IAR EWARM 8.3?

### ISSUE THREAD

**Issue by zhyjason** [ARMmbed/DAPLink#1050]
![image](https://github.com/ARMmbed/DAPLink/assets/41561849/ab688baa-378c-407b-a753-075f4272bf25)

**Comment by mbrossard** [comment]
What DAPLink device are you using. If it appears as storage can you share the content of the `DETAILS.TXT` file?

**Comment by LaoChang2012** [comment]
I am opposite to you.  I can work with IAR, but MDK prompts RDDI-Error.
