### ISSUE TITLE
Can you tell me the implementation mechanism of USB pop-up U disk?

### ISSUE THREAD

**Issue by wdfk-prog** [ARMmbed/DAPLink#1080]
### Can you tell me the implementation mechanism of USB pop-up U disk?

- I have achieved the U disk pop-up function;But I am a composite device, with a virtual serial port +U disk function
- The USB flash drive eject scheme I implemented is to uninstall and enumerate a new CDC descriptor after detecting the eject event sent by the PC.Doing so the virtual serial port will change and no longer be the same
- I think another way is to eject the USB flash drive, do not uninstall the device, but re-enumerate the original descriptor, but the end point of the USB flash drive is not registered

### I found that DAP-LINK also implemented CDC+MSC device implementation, and the virtual serial port was not affected when the execution U disk popped up;Can you tell me how you did it?No corresponding logic found in the code

**Comment by mathias-arm** [comment]
I am sorry, I don't know the answer. I don't think we change the descriptors.
