### ISSUE TITLE
USB endpoint calculations check issue

### ISSUE THREAD

**Issue by awais-ublox** [ARMmbed/DAPLink#284]
The distinct endpoint validation check for HID and MSC interface requires fixing, as USBD_HID_EP_INTIN is not compared with **USBD_MSC_EP_BULKOUT**

For file(s) usb_config.c in hic_hal:

#if ((((USBD_HID_EP_INTIN   == USBD_MSC_EP_BULKIN)  || \
       (USBD_HID_EP_INTIN   == **USBD_MSC_EP_BULKIN**)))|| \
      ((USBD_HID_EP_INTOUT  != 0)                   && \
       (USBD_HID_EP_INTOUT  == USBD_MSC_EP_BULKIN)  || \
       (USBD_HID_EP_INTOUT  == USBD_MSC_EP_BULKOUT)))
#error "HID and Mass Storage Device Interface can not use same Endpoints!"

**Comment by c1728p9** [comment]
Thanks for reporting this @awais-ublox. I created a PR https://github.com/ARMmbed/DAPLink/pull/352 to fix this.

**Comment by awais-ublox** [comment]
You are welcome :)

**Comment by c1728p9** [comment]
Closing since the fix was merged
