### ISSUE TITLE
MSD command start_bl.act puts K64F to MAINTENANCE mode

### ISSUE THREAD

**Issue by ErkkiMehtala** [ARMmbed/DAPLink#332]
I tried to put K64F to BOOTLOADER mode, by copying start_bl.act to DAPLINK drive like told in DAPLink/docs/MSD_COMMANDS.md. But instead device goes to MAINTENANCE mode. I tried
still copying daplink 244 to drive, it reseted but not mounting then at all. Only available mode is now maintenance (instead of bootloader by connecting with reset button on).

This has happened to 2 devices. Originally I had daplink 243 and automation mode on.

**Comment by c1728p9** [comment]
Hi @ErkkiMehtala, MAINTENANCE mode is bootloader mode. The drive name was changed from BOOTLOADER to MAINTENANCE when the DAPLink project was created from CMSIS-DAP.
