### ISSUE TITLE
USB / CDC / UART problem on win10 unsupported command

### ISSUE THREAD

**Issue by cederom** [ARMmbed/DAPLink#339]
A problem was reported on win10 USB UART reports unsupported command, this needs to be investigated and fixed..

**Comment by cederom** [comment]
As discussed with @c1728p9 who identified the issue this is an intermittent failure when multiple devices are tested on win10 host, error is reported by Python, needs more investigation..

**Comment by brianesquilona** [comment]
Cannot reproduce this issue so will close it.
