### ISSUE TITLE
DAPLink, DAP_JTAG, LPC11U35

### ISSUE THREAD

**Issue by Lean966** [ARMmbed/DAPLink#391]
I am trying to include in the DAPLink Hw, the JTAG option. I define DAP_JTAG, the SWD work ok in Keil,  JTAG mode doesn't work. 
I found some bugs:
// TDI Pin                                      PIO0_17
#define PIN_TDI_PORT                 17        //I changed by 0
#define PIN_TDI_BIT                     17
// SWO/TDO Pin                           PIO0_9
#define PIN_TDO_PORT                9        //I changed by 0
#define PIN_TDO_BIT                    9
However, after these fixed still doesn't work. Any ideas?

**Comment by flit** [comment]
What probe circuit and board are you using? Does the circuit actually support the JTAG TDI/TDO signals (I'm guessing yes since you list port pins for these signals)? Do you have a schematic you can share?

**Comment by Lean966** [comment]
I attached the Schematic. The previuos version of CMSIS-DAP worked ok with JTAG option. However this new repo, doesn't work. May be there is a copy and paste mistake... I don't know...
[RDAPLink v1.0.pdf](https://github.com/ARMmbed/DAPLink/files/1717069/RDAPLink.v1.0.pdf)

**Comment by Lean966** [comment]
Hi, could you find something? Thank

**Comment by cederom** [comment]
Hey @Lean966, some questions/hints:
* Have you tried with different Targets?
* Did that interface work with JTAG before?
* Are you sure that your target does not need nTRST signal?
* Have you tried connecting under reset etc?

**Comment by Lean966** [comment]
Hi @cederom,
Have you tried with different Targets? Yes, and with different programer too (J-link). The CMSIS-DAP v1.0 (before DAPLink project) worked with JTAG/SWD and the same Hw DAP. However with this SW version doesn't work. Regrettably, I don't have back up of this source. 
Did that interface work with JTAG before? Yes
Are you sure that your target does not need nTRST signal? LPC1768 and STM32F407. I never conected this pin and worked
Have you tried connecting under reset etc? Yes.
I am testing with Keil, with J-Link (Pro and OB) worked ok, CMSIS-DAP v1.0 worked too (all with different targets)
I surfing the sources, and I saw that it changed. I found some issue (as I wrote up) in the source code. And I have the feeling there is something there. 
For more info, for compiling I am use Keil 5 and migrating libraries. 
Thank and I wait your feedback

**Comment by cederom** [comment]
Are you sure JTAG is selected as transport not SWD in your code? It is not runtime selectable..

If DAPLink worked for you before on the same HIC hardware and the same Target.. please try reverting to release 246, 245, 244, 243, etc .. so we could see if that worked before and what change could break things.. you may use `git bisect` for that..

**Comment by Lean966** [comment]
Ok. I will try the previous version. What is HIC? I need to trace when these mistake sentences appeared:
_TDI Pin PIO0_17_
#define **PIN_TDI_PORT 17** //I changed by 0
#define PIN_TDI_BIT 17
_SWO/TDO Pin PIO0_9_
#define **PIN_TDO_PORT 9** //I changed by 0
#define PIN_TDO_BIT 9
If I found something I tell you
