### ISSUE TITLE
interface binary in releases for KL82Z has wrong offset

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/DAPLink#405]
The offset for FRDM-KL82Z should be 0x5000.  This is not to be confused with the FRDM-K82F, which uses offset 0x8000.  The releases need to be updated and any configuration fixed so that future release scripts provide the right file for KL82Z (0x5000 offset!)  

Thanks!

**Comment by brianesquilona** [comment]
Confirmed that the current config already has this fix.
