### ISSUE TITLE
DAPLink without RTOS?

### ISSUE THREAD

**Issue by xcvista** [ARMmbed/DAPLink#418]
Is there any feasible way to build DAPLink without RTOS involvement? This would allow even cheaper debug interfaces, for example one based on STM32F042F6P6 (32kB Flash, TSSOP-20 package) or even ATSAMD11C14 (16kB Flash, SO-14 package) chips

If so, what files need be extracted? If not, is there any pointer or documentation on how to reimplement the CMSIS-DAP protocol?

**Comment by cederom** [comment]
Hey @xcvista, not really, this is part of DAPLink design.. the RTOS overhead is really minimal and gives lots of versatility.. one day even DAPLink may be rewritten to work on ARM mbedOS..

CMSIS-DAP code is kind of submodule located at: https://github.com/ARMmbed/DAPLink/tree/master/source/daplink/cmsis-dap 

You may want to rewrite that part with HID Debug or UMS Flashing plus the USB stack if you think your time is worth the result.. still $1 IC seems cheaper..

**Comment by xcvista** [comment]
@cederom I have a working USB stack already that targets extremely small STM32 chips and it can be entirely interrupt pumped (so it don't waste CPU cycles unless need to) The HID debug is what I need to run on top of that. As of the UMS I have a drastically different use for it, being used for storing the program in the box and flash targets offline, so the DAPLink UMS Flash won't work for me as-is. I also need a separate CDC channel.

**Comment by xcvista** [comment]
The STM32F042 chips are what I found as "just enough peripherals" chips: it has the perfect amount of pins and peripherals to implement the features I have in mind, and stepping to any other model means introducing unused peripherals or a lot of unused pins. Too bad the F042 doesn't have a lot of Flash to accommodate the RTOS, hence I am seeking bare metal solutions.

**Comment by therealprof** [comment]
@xcvista I agree. I love that chip, I basically throw it on every design I do just for good measure and it really has a killer selection of peripherals. The next step up would be the F072 which also has more flash but it's not available as TSSOP. Being able to use that as DAPLink programmer would be outstanding.

**Comment by cederom** [comment]
You may also talk to Cypress Semiconductor, they have some sort of peripheral matrix in their PSoC, and you may be able to negotiate good price per chip that only uses selected peripherals :-)

**Comment by therealprof** [comment]
@cederom Yeah, but they're awkward to use and they only support development with a GUI based Windows-only IDE which sucks rocks. They also have their own CMSIS-DAP implementation called KitProg but that's mostly 5V only and the chips are really somewhat tricky to use in own designs.

**Comment by cederom** [comment]
Yea, STM ROX, and they have really good support for Open-Source :-) My friends that squeeze every penny out of design told me about the trick with Cypress, but I did not use that myself, just a hint for you guys :-)

**Comment by flit** [comment]
Closing issue. The DAPLink interface will always use an RTOS as an integral part of its design. The RTOS will become even more important as we add more advanced features such as power monitoring and IO expansion. There is a chance that the bootloader might become RTOS-less in order to reduce size, but no guarantee.
