### ISSUE TITLE
fix typo

### ISSUE THREAD

**Issue by tarokajya** [ARMmbed/DAPLink#433]
This patch will fix typo.

--- read_uid.h.orig     Mon Feb 12 14:01:00 2018
+++ read_uid.h  Mon May 21 13:49:10 2018
@@ -25,7 +25,7 @@
 #include "stdint.h"

 #ifdef __cplusplus
-}
+extern "C" {
 #endif

 void read_unique_id(uint32_t *id);

**Comment by flit** [comment]
Can you please create a pull request for this patch? Thanks.

**Comment by tarokajya** [comment]
O.K. Now I created a pull request. Thank you.

**Comment by flit** [comment]
Thank you 😄
