### ISSUE TITLE
Error: The transfer timed out.

### ISSUE THREAD

**Issue by panuniverse** [ARMmbed/DAPLink#440]
1 Compiling the DAPLink's code about TMPM366FYXBG for target MCU TMPM4G.
2 Programming the  .bin to TMPM366FYXBG.
3 Programming the TMPM4G.bin by TMPM366FYXBG, but the FAIL.TXT shows "**# The transfer timed out**".

**Comment by brianesquilona** [comment]
I'm not sure what interface chip and target are we dealing with here, so I will close this issue, feel free to reopen it if this is still relevant.

**Comment by cederom** [comment]
I have noticed such behaviours on some boards that had reset problem - reset unify was supposed to fix that - @panuniverse  you can try with the alternative reset code: https://github.com/ARMmbed/DAPLink/pull/371
