### ISSUE TITLE
Microchip don't recommend SAM3U for new designs, neither do NXP with LPC1135U

### ISSUE THREAD

**Issue by tekbee** [ARMmbed/DAPLink#459]
If both of these chips are NRND that only leave the KL25/26/20 series or the apparently upcoming 'MAX35520'

Which chip do ARM recommend for new designs if not the SAM3U

**Comment by flit** [comment]
Where do you see the statement that the LPC11U35 is NRND? I checked nxp.com, and it [shows as active](https://www.nxp.com/products/processors-and-microcontrollers/arm-based-processors-and-mcus/lpc-cortex-m-mcus/lpc1100-cortex-m0-plus-m0/64kb-flash-12kb-sram-hvqfn32-package:LPC11U35FHI33?tab=Buy_Parametric_Tab&amp;fromSearch=false).

My recommendation for new designs is the NXP KL27Z. It is a nice step up from the KL26Z, with bigger memories, crystal-less USB, and a ROM bootloader, yet compatible with the KL26Z. (Crystal-less USB support requires a minor code change in the USB driver.) It also has the FlexIO peripheral, which could theoretically be used to improve SWD performance.

And we can and will add new HICs. Work has been done to support the K26F (with high speed USB), which will be brought in shortly. The LPC54608 would make a very good HIC. #465 adds support for the STM32F103.

**Comment by tekbee** [comment]
Altium designer lists the LPC11U35 as NRND I am not sure which database this is being pulled from though. Thanks for your help
