### ISSUE TITLE
DAPLink flashing isn't working after hardfault crash

### ISSUE THREAD

**Issue by KariHaapalehto** [ARMmbed/DAPLink#467]
Step to procedure error:
- Create mbed-os version, which will hardfault e.g Null pointer write. Flash the sw and verify from traces that hardfault did happen.
- Correct you sw and try to flash it. HW will blink the led just couple times and the "FAIL.TXT"-file is created to daplink-drive with following text:
"error: The interface firmware FAILED to reset/halt the target MCU
type: target"
and no new is flashed.

-Only way to recover from this issue is manually press reset button down before sw copy starts and release the reset button while coping.

This error has been seen with several new MTB+MCB compination. I have seeen it with MTB_USI_BN_BM_22, MTB_ADV_WISE_1530 and MTB_MXCHIP_EMW3166. 
I have seen this error with DAPLink versions 0246 and 0244.

**Comment by brianesquilona** [comment]
Fixed in the PR #480
