### ISSUE TITLE
microbit KL26 bootloader LED constantly flahsing

### ISSUE THREAD

**Issue by microbit-carlos** [ARMmbed/DAPLink#477]
I've recently built the micro:bit KL26 bootloader from current master (5b94914), and whenever it is running (micro:bit in maintenance mode), the DAPLink LED won't stop flashing.

This issue is not present on the 0247 release, only current master.

Build files: [0247-5b94914.zip](https://github.com/ARMmbed/DAPLink/files/2288729/0247-5b94914.zip)

**Comment by brianesquilona** [comment]
#481

**Comment by carlosperate** [comment]
Thanks @brianesquilona!

**Comment by microbit-carlos** [comment]
Fixed in https://github.com/ARMmbed/DAPLink/pull/481.
