### ISSUE TITLE
pipeV - Micro:bit 

### ISSUE THREAD

**Issue by bsimmo** [ARMmbed/DAPLink#483]
I just transferred the micro:bit hex from the 
https://github.com/ARMmbed/DAPLink/releases REL v0247
in maintenance mode and now it doesn't work. just has pipeV scrolling and stayed in maintenance mode after a disconnect/reconnect
so I tried putting 0243 as (from microbit site over it https://support.microbit.org/support/solutions/articles/19000019131-how-to-upgrade-the-firmware-on-the-micro-bit 
and now it just scrolls pipeV and the computer doesn't see it. (or see it trying maintenance mode )

Have I buggered it ?
what's pipeV

**Comment by carlosperate** [comment]
Is the micro:bit display scrolling "pipev"? In that case that would be from the last program flashed to the micro:bit, DAPLink doesn't have access to the LED matrix.
When flashing a DAPLink hex file into maintenance mode, does the flashing complete successfully? Is there fail.txt in the drive after the micro:bit disconnects and connects again?

**Comment by bsimmo** [comment]
Yes on the display.

I'll have a look again when I can (not near it at the moment).
I do have a few others to test on.

I dropped it over, waited a while, I think it went ping pong in Windows and
then I disconnected and reconnected

I'll wipe out any old drivers/attachments hidden in Device Mange as wellin
case they are stopping it from seeing the device.

End of the week hopefully.

**Comment by bsimmo** [comment]
For the info, I tried to fix it back then but nothing worked.
Left it for a while (akak until today)

Downloaded the new firmware, place a test one in Maintenance and flashed (v0250).
Worked, and tested ith simple MakeCode hex.
So flashed the pipeV one and it flashed fine and worked etc..
case closed.

Of course no idea if a windows10 update fix along the way or a firmware fix.
