### ISSUE TITLE
LPC546XX Fails to program above 256K

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/DAPLink#501]
Board: LPC54608
DAPLink Version: 0249

Flashing a binary < 256 KBytes works fine.  

Flashing a binary > 256 KBytes results in all 0's at 256 KBytes (0x40000) and above.  So applications larger than 256K will crash because instructions will not be present in the upper half as expected.  

Looks like the configuration is correct for 512K flash size.  I suspect a problem with the flash algorithm itself.

**Comment by maclobdell** [comment]
@mmahadevan108

**Comment by maclobdell** [comment]
cc @ashok-rao  This likely affects FF_LPC546XX also.

**Comment by flit** [comment]
Can this ticket be closed now that #504 has been merged?
