### ISSUE TITLE
Silent failure in drag&drop flashing with non-sequential addresses

### ISSUE THREAD

**Issue by microbit-carlos** [ARMmbed/DAPLink#506]
When flashing via drag and drop of a hex file, DAPLink needs the addresses to be sequential: 

https://github.com/ARMmbed/DAPLink/blob/ab7abed209eb166a98a8ecc69b05a4dcbe86adc6/source/daplink/drag-n-drop/flash_manager.c#L127-L134

If we have a file that first tries to write to address `0x1000_10C0` and then to `0x0000_0000` (example file [uicr-micropython-pycode.hex.txt](https://github.com/ARMmbed/DAPLink/files/2420961/uicr-micropython-pycode.hex.txt)) we get an clear error in the form of a fail.txt and assert.txt files:

```
error: An internal error has occurred
type: internal
```

```
Assert
File: ..\..\..\source\daplink\drag-n-drop\flash_manager.c
Line: 131
Source: Application
```

This is fine, but if we first start to write from address `0x0000_0000`, then jump to address `0x1000_10C0` and then jump back to `0x0003_E000` (example file [micropython-uicr-pycode.hex.txt](https://github.com/ARMmbed/DAPLink/files/2420966/micropython-uicr-pycode.hex.txt)), then the flashing fails silently.

The block starting at `0x0000_0000` and `0x1000_10C0` are flashed correctly, but the block starting at `0x0003_E000` is not flashed, which is expected, but there is no fail.txt or asset.txt files present.

Tested with DAPLink 0243 and 0250, in a micro:bit.

A test on DAPLink 0241 produces an assert.txt file but no fail.txt.

Although I understand why the sequential addresses enforcement has been included, it is worth noting that in contrast DAPLink 0234 seems to cope with this specific example correctly and flashes all areas as expected without showing any errors.

**Comment by flit** [comment]
@brianesquilona I'm surprised #503 didn't fix this problem. Any idea what the difference is?

**Comment by brianesquilona** [comment]
This is definitely worth checking but I can see tat the the end address was detected by the decoder, so it did not continue.

**Comment by brianesquilona** [comment]
@microbit-carlos I have added #510, but these changes will be reviewed for side effects. Can you help verify with your hex files. Thanks

**Comment by microbit-carlos** [comment]
Hi @brianesquilona, yes I can test some of the hex files's we've got (the only odd ordering is this UICR area I've mentioned here). Is there any specific pattern/ordering in the hex file you want to test?

**Comment by brianesquilona** [comment]
Thanks @microbit-carlos, you can verify your hex files that met your requirements. Just a note, non-ascending address support will trigger a sector setup, which may erase a page if supported, or writes 0xFF on addresses on sector boundary if the input address given is not on sector boundary.

**Comment by microbit-carlos** [comment]
Apologies @brianesquilona, I haven't been able to test this yet and I will be away for a few days. I hope this can wait until Tuesday when I'm back.

**Comment by brianesquilona** [comment]
@microbit-carlos it's fine, PR will always be there :)
