### ISSUE TITLE
build_release.bat does not work

### ISSUE THREAD

**Issue by AdamKoltys** [ARMmbed/DAPLink#533]
[OS]: **Windows10**

When I try to run toosl\build_release.bat script  without any parameters I am getting error:
**( was unexpected at this time.**
From  I see the problem is that %project_tool% is not defined

**Comment by brianesquilona** [comment]
@AdamKoltys Thanks for testing it, I have updated the script here #534. If you do not want to update the script just pass any other argument except for mbedcli.

**Comment by AdamKoltys** [comment]
It is working now.
