### ISSUE TITLE
Feature Request: Option to Disable the USB Disk

### ISSUE THREAD

**Issue by awneil** [ARMmbed/DAPLink#536]
Copied from https://github.com/mbedmicro/CMSIS-DAP/issues/98

The "USB disk" is great when you just have a .bin file you want to drop onto the target.

But, when doing "conventional" development - downloading & debugging via the debug interface - I find it annoying to have the "USB disk" keep popping up every time the board is restarted.

It would be useful to be able to disable it when not wanted.

**Comment by therealprof** [comment]
I fully agree, especially when moving between boards having to eject the MSD (or ack the warning) can get a bit long in the tooth.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by awneil** [comment]
@theotherjimmy  - Thanks for your support!

Although I acknowledged in the OP that I do see the point of the MSD, it is a feature that I very rarely (if ever) use. I (almost) invariably do "conventional" development - so the MSD is  (almost) invariably a nuisance.

**Comment by flit** [comment]
You aren't the only ones who are asking for this. We are taking this request seriously, and plan to enable a build without MSD or flash programming.

**Comment by awneil** [comment]
@flit - thanks.

So the plan is for a build-time option - rather than a run-time configuration?

I guess the downside of that is ensuring that the board makers provide both builds to end users?

For completeness (unlikely to be an option that I would ever want), would there also be an option to disable the virtual COM port?

**Comment by cederom** [comment]
Configuration like this could be done in runtime in bootloader and stored
for future boots.. then user could change the features in a safe place and
only one firmware would be supplied..?

--
CeDeROM, SQ7MHZ, http://www.tomek.cedro.info
