### ISSUE TITLE
Where find the firmware files?

### ISSUE THREAD

**Issue by tarasinf** [ARMmbed/DAPLink#548]
As mentioned in the user [guid](https://github.com/ARMmbed/DAPLink/blob/master/docs/USERS-GUIDE.md), "From there copy the appropriate firmware onto the drive". 

Question is, what is the location of the "firmware" file?

**Comment by tarasinf** [comment]
Found the solution. Would be nice to add to the doc:https://armmbed.github.io/DAPLink/

**Comment by flit** [comment]
This is already covered in the README.md under the Releases section, the sentence/link "The current release builds and instructions for updating DAPLink interface firmware is hosted on the DAPLink release site." However, I created #554 to add a link to the users' guide.

Closing this issue.
