### ISSUE TITLE
Support for Programming external target on SLSTK3701A

### ISSUE THREAD

**Issue by ghost** [ARMmbed/DAPLink#552]
The [EFM32GG11 starter kit](https://www.silabs.com/products/development-tools/mcu/32-bit/efm32-giant-gecko-gg11-starter-kit) is capable of flashing external targets via its external debug interface. DAP Link drag and drop does not seem to work when configured in this mode however. FAIL.txt is present when device reboots. 

This functionality is particularly useful because it is currently the only way to run greentea tests against a custom target.

**Comment by flit** [comment]
This is likely caused by some difference in the circuit when using the external debug interface.  If you can identify what the issue is, then we could look at incorporating a fix. Although, it might require a special build.
