### ISSUE TITLE
Nit: Inaccurate comment

### ISSUE THREAD

**Issue by loverdeg** [ARMmbed/DAPLink#579]
https://github.com/ARMmbed/DAPLink/blob/master/source/hic_hal/atmel/sam3u2c/IO_Config.h#L32

![image](https://user-images.githubusercontent.com/24318071/52237335-3d972880-2897-11e9-9229-59b281d8f55a.png)

**Comment by mathias-arm** [comment]
This was fixed in 49f6eef
