### ISSUE TITLE
Switch to Mbed USB stack

### ISSUE THREAD

**Issue by flit** [ARMmbed/DAPLink#581]
As part of the plan to support gcc, we need to switch from the current Keil USB middleware stack to the new Mbed OS USB stack. The new stack is currently on the [feature-hal-spec-usb-device](/ARMmbed/mbed-os/tree/feature-hal-spec-usb-device) of mbed-os.

Child of #197

**Comment by eleenest** [comment]
Hi,

Is there any activity on this task?
We are considering this as an intern project for this summer, if it is not being actively worked on (with the goal of being able to use this on a STM32H based debug board, with other functionality).

Eric
