### ISSUE TITLE
Problem when IR length is 8 bit

### ISSUE THREAD

**Issue by PetShelford** [ARMmbed/DAPLink#597]
I've been trying to set IR length 8 bit, but it leads to invalid scans of IDCODE, APACC, DPACC and ABORT registers. The problem actually is in 'C- defines' where 4 MSB bits defined as '0'. The chip I'm targeting wants it as '1'. So the question: does anybody try to use DAPLink with target which has 8-bit IR length?

**Comment by flit** [comment]
What DAPLink build are you using that supports JTAG?

**Comment by PetShelford** [comment]
Well, I've been told it is CMSIS-DAP v5_224. It is for LPC-Link2 and is a part of LPCScrypt software.

**Comment by flit** [comment]
I *think* that is the NXP-proprietary firmware for LPC-LinkII. DAPLink is different, open source, firmware developed by Arm. I know the NXP tools team, so let me follow up on it and I'll get back to you here.

**Comment by flit** [comment]
What device are you using that has an 8-bit IR? We've never seen a device with this IR length yet.

Even though the firmware you are using is not DAPLink, we want to ensure that >4-bit IR length is supported in DAPLink (and other Arm debug probes like ULINK).

And sorry, I never heard back from the NXP tools team! However, the LPC-LinkII firmware is known to be using the reference CMSIS-DAP code released as part of the CMSIS package. So if an 8-bit IR doesn't work with LPC-LinkII, then it probably won't work with any other probe that uses the reference CMSIS-DAP code.

**Comment by flit** [comment]
We've confirmed that it's the reference CMSIS-DAP code that does not support an 8-bit IR.
