### ISSUE TITLE
Firmware doesn't fit in FRDM-K66F

### ISSUE THREAD

**Issue by zepperik** [ARMmbed/DAPLink#610]
When mounted as a "bootloader" drive, Windows claims that it needs 4kB of extra space.  I need to boot into Linux to successfully copy the firmware.

**Comment by brianesquilona** [comment]
@zepperik, if you have flash the interface, try to drag and drop the k20dx_bl bootloader to update it. New bootloader drive will have "MAINTENANCE" drive name. Let me know if you need the binary.

**Comment by zepperik** [comment]
The link: https://armmbed.github.io/DAPLink/?board=FRDM-K66F gives me a file called 0253_k20dx_frdmk66f_0x8000.bin.  (This link also included this github link.)  The board shows up as BOOTLOADER when plugged in with the reset button held down.  Dragging and dropping this file into the BOOTLOADER drive gives me the error about not having enough space.

**Comment by brianesquilona** [comment]
[k20dx_bl_crc.zip](https://github.com/ARMmbed/DAPLink/files/2984373/k20dx_bl_crc.zip)
You can try this bootloader to update the bootloader in K66F, after the interface update of 0253_k20dx_frdmk66f_0x8000.bin. Flash this bin in interface mode. Let me know if you were able to change the bootloader (to MAINTENANCE) by this method.

**Comment by zepperik** [comment]
Thanks.  I already updated it by copying the binary while in Linux.  I didn't expect such a quick response.  I was going to update the bootloader, but in the link: https://os.mbed.com/blog/entry/DAPLink-bootloader-update/ the FRDM-K66F is not listed so I didn't want to risk bricking another board.

**Comment by brianesquilona** [comment]
[k20dx_bl_crc.zip](https://github.com/ARMmbed/DAPLink/files/2984592/k20dx_bl_crc.zip)
@zepperik 
I think I have made a mistake, the master branch have a different memory map now for the bootloader so the last one will not work, try this one instead.
