### ISSUE TITLE
Can  i build DAPLink (stm32f103xb HIC ) using GCC_ARM toolchain ?

### ISSUE THREAD

**Issue by bagyavinoth** [ARMmbed/DAPLink#625]
Hello,
I use this evaluation board : [Link](https://www.st.com/en/evaluation-tools/stm32f779i-eval.html)
Where the debug unit MCU is "STM32F103CBT6" & the application MCU is "STM32F779NI".
Debug unit supports ST-LINK firmware which is a closed source. I would like to use "DAPLink" in the debug unit.
As per my understanding, HIC stm32f103xb should support. Right ? Ofcourse the target support to be added for "STM32F779NI"

But my development environment is GCC_ARM. Can i build DAPLink with GCC_ARM ?

Regards,
Vinoth.

**Comment by flit** [comment]
Currently DAPLink only builds with Arm Compiler 5. Please see #197 for details.

Closing as a duplicate.
