### ISSUE TITLE
Win 7 serial driver issue - Does board ID have to be added to a list?

### ISSUE THREAD

**Issue by malavikasajikumar** [ARMmbed/DAPLink#643]
We have a new controller board that is supported in mbed-os. The board is not officially released in Mbed. So the board ID is not known to "mbed --list" command and we currently mock this addition using the -m option. 

When we try to install serial drivers for the board on a Win 7 machine, we get the error, "no mbed microcontroller found". 
1. Is there a list where the board needs to be added in order to be able to install serial drivers? The reason for this question is that installation of serial drivers require that the board be plugged in. 
2. How does the driver installation know to identify an mbed supported board? Is this part of the official release? 

The board has DAPLink based on Freescale MK20DX128 microcontroller.

**Comment by flit** [comment]
The Win 7 serial driver does not use board IDs.

When do you see the "no mbed microcontroller found" error? During serial driver installation?
