### ISSUE TITLE
DAPLink can't be detected in MDK-ARM V5

### ISSUE THREAD

**Issue by ChinaXiaoMao** [ARMmbed/DAPLink#649]
I made a DAPLink using STM32F103. It can't be detected in MDK-ARM V5. When I open the setting of CMSIS-DAP in Keil V5, the LED turn on a short time but no debug unit device found. I get these message in Bus Hound
![image](https://user-images.githubusercontent.com/34369324/64470839-20537100-d17c-11e9-8a12-cf64b1d093b3.png)
But it can be detected in EWARM V8. When I start a debug sesson in EWARM, I get these message in Bus Hound
![image](https://user-images.githubusercontent.com/34369324/64470907-141be380-d17d-11e9-9869-9108950f8da3.png)

**Comment by 0xc0170** [comment]
What version of MDK? What about pyOCD also having issues?

**Comment by ChinaXiaoMao** [comment]
> What version of MDK? What about pyOCD also having issues?

5.28a

**Comment by flit** [comment]
There is a known issue with MDK where it does not detect a CMSIS-DAP interface with interface number greater than 0.

**Comment by 0xc0170** [comment]
It has not yet been fixed in MDK, we will follow up on this issue with MDK team. Thanks @flit !

**Comment by ChinaXiaoMao** [comment]
@0xc0170 
I tried stm32f103xb_stm32f103rb_if and it works. Maybe only stm32f103xb_if doesn't work.

**Comment by 0xc0170** [comment]
These two differ in the records (what files are included). There was this recent change https://github.com/ARMmbed/DAPLink/pull/629 that could make the difference for `stm32f103xb_if `

**Comment by flit** [comment]
@ChinaXiaoMao The issue in MDK has been fixed. Please see this Keil knowledge base article with an attached updated CMSIS-DAP driver DLL: http://www.keil.com/support/docs/4170.htm. An

**Comment by 0xc0170** [comment]
I'll close this as resolved.
