### ISSUE TITLE
Does the DAPLink support debugging risc-v ? 😅

### ISSUE THREAD

**Issue by balanceTWK** [ARMmbed/DAPLink#650]
Need to modify the source code to support risc-v jtag ?  囧rz

🤣

**Comment by 40Grit** [comment]
For a giga devices part?

Does risc-v even have standard debug silicon yet? Particularly for MCU's?

**Comment by balanceTWK** [comment]
> For a giga devices part?
> 
> Does risc-v even have standard debug silicon yet? Particularly for MCU's?

yes ,giga devices.

I have a development board. ( GD32VF103 RISC-V 32-bit MCU evaluation Board ) there is a gd-link on the board and I found that gd-link was identified as cmsis-dap.

**Comment by flit** [comment]
Sorry, DAPLink doesn't support RISC-V.

Very interesting that gd-link identifies as CMSIS-DAP. Do you mean the USB device product name includes "CMSIS-DAP"?

**Comment by 40Grit** [comment]
additionally what part number is the gd-link controller?

**Comment by balanceTWK** [comment]
I'm just detecting it with MDK

![image](https://user-images.githubusercontent.com/30776697/64488493-35fb9000-d27b-11e9-9896-b136e904e3c0.png)

**Comment by 0xc0170** [comment]
> Very interesting that gd-link identifies as CMSIS-DAP. Do you mean the USB device product name includes "CMSIS-DAP"?

From their documentation : "GD-Link adapter is a three-in-one multi-function development tool for GD32 series of MCUs. It provides CMSIS-DAP debugger port with JTAG/SWD interface".

I assume this is the debug target; https://github.com/ARMmbed/DAPLink/pull/538 ?

@balanceTWK Before you ask a question, look at documentation and source code, you can find your answer there 😉
