### ISSUE TITLE
How to build M484 project?

### ISSUE THREAD

**Issue by Kevincoooool** [ARMmbed/DAPLink#683]
when I  progen generate -t uvision
I got this:
RuntimeError: Target m485sidae is not supported. Please add them to https://github.com/project-generator/project_generator_definitions

**Comment by Kevincoooool** [comment]
I changed the target chip to stm32f103xb, then the mdk project can be generated normally,  then downloaded to M484SIDAE, the serial port works normally, and the program can be downloaded to the target chip, but it is very slow and it seems that the internal high-speed PHY is not used

**Comment by 0xc0170** [comment]
> RuntimeError: Target m485sidae is not supported. Please add them to https://github.com/project-generator/project_generator_definitions

This error messaage comes from project generator, the MCU set for your project is not supported for uvision. You can add it to  https://github.com/project-generator/project_generator_definitions. The project contains more information how to do it.


@ychsu-tf Please review

**Comment by ychsu-tf** [comment]
Hi,
Target m485sidae has been added to project_generator_definitions recently.
Please update it to the latest version v0.2.40.

**Comment by 0xc0170** [comment]
> Please update it to the latest version v0.2.40.

This should be resolved, I'll close the issue.
