### ISSUE TITLE
Provide DAPLink version via WebUSB

### ISSUE THREAD

**Issue by microbit-carlos** [ARMmbed/DAPLink#723]
Right now the DAPLink version cannot be obtained via WebUSB, having this information would be really useful for the micro:bit online editors and other DAPLink consumers. Quite useful as well if we ever need to request users to update their DAPLink firmware.

**Comment by flit** [comment]
In the latest code on master, the DAP_Info command will return the DAPLink version string for the `DAP_ID_FW_VER` property.

**Comment by flit** [comment]
Update: I discussed this with the CMSIS team ([#962](https://github.com/ARM-software/CMSIS_5/issues/962)). The `DAP_ID_FW_VER` value is intended to be the CMSIS-DAP protocol version. So changing it to report the DAPLink version is non-compliant. 

Instead, I proposed we define a new `DAP_ID_PRODUCT_FW_VER` (0x07) info value that is dedicated to the product's firmware version. This is implemented in CMSIS PR [#973](https://github.com/ARM-software/CMSIS_5/pull/973).

I've already [implemented](https://github.com/flit/DAPLink/tree/feature/cmsis_dap_version) the change for DAPLink, and will merge when the CMSIS-DAP pull request is merged.

**Comment by microbit-carlos** [comment]
Thank you Chris!

@thegecko I guess this is something that could go into DAPJs as well when is all merged.

CC FYI @pelikhan @mmoskal

**Comment by thegecko** [comment]
> I guess this is something that could go into DAPJs

Yup, looks like a simple extension

**Comment by mathias-arm** [comment]
> I've already [implemented](https://github.com/flit/DAPLink/tree/feature/cmsis_dap_version) the change for DAPLink, and will merge when the CMSIS-DAP pull request is merged.

This was done in #776. Can we close the issue?

**Comment by thegecko** [comment]
Unfortunately the chosen address for this data clashes with an existing CMSIS-DAP entry (see https://github.com/ARM-software/CMSIS_5/issues/962#issuecomment-825497410). This should be resolved, ideally.

**Comment by microbit-carlos** [comment]
@flit just wanted to confirm if the clash mentioned by Rob is resolved already and the version in `develop` is good to go?

**Comment by flit** [comment]
Yes, that's all fixed for some time now.
