### ISSUE TITLE
Microbit DAPlink 0249 BUG?

### ISSUE THREAD

**Issue by zfm076** [ARMmbed/DAPLink#736]
**my microbit NRF51822 IC code:**
```
while(1)
{
  microbit.serial.send(microbit.thermometer.getTemperature());
  microbit.sleep(50);    //Send the temperature to the computer every 50ms
}
```
**Problem:**
**In my computer :**
It worked all day, The yellow light behind the board also blinks.There is no problem.

**But it's on my friend's computer:**
Can only work normally for a few minutes or ten minutes,Time is not fixed. The yellow light behind the board is usually on, not flashing,My friend's computer can't get data via USB. Then I change the board back to my computer ,it was able to work a full day. Why? I've been searching for a week and I can't find the reason. Do you have this problem? What do you think is most likely the problem?

**Microbit Interface Parameter:**  
Daplink Mode: Interface
Interface Version: 0249
Bootloader Version: 0243

**Comment by 0xc0170** [comment]
Does older firmware work (is this specific to 0249?) ?

**Comment by zfm076** [comment]
> Does older firmware work (is this specific to 0249?) ?

Interface Version: 0249   ,This is working fine on my computer.
