### ISSUE TITLE
build without drag-n-drop (MSD) support

### ISSUE THREAD

**Issue by moyoumos** [ARMmbed/DAPLink#742]
i am  modifiying  the daplink firmware code so that there is no drag-and-drop (MSD) support; and haven't yet material to test on;  i post here to know if it is suffisiant to \#_undef_ all occurances of **DRAG_N_DROP_SUPPORT** in source files and build daplink FW with only CMSIS-DAP debug channel (HID) and  virtual com port (CDC ) support? doing so i will use PyOCD to flash the target firmware via the debug channel.

**Comment by 0xc0170** [comment]
It should be possible just not using `DAPLink/records/daplink/drag-n-drop.yaml` . This one defines that macro and adds sources.
