### ISSUE TITLE
My board can not run the link

### ISSUE THREAD

**Issue by lilang1746** [ARMmbed/DAPLink#767]
I use the https://github.com/ARMmbed/mbed-HDK-Eagle-Projects board ，but the link can not read by my computer

**Comment by 0xc0170** [comment]
Hi, please provide detailed report what is not working. However this could be related to the eagle projects or something else than Daplink.

**Comment by lilang1746** [comment]
> 嗨，请提供详细的报告，什么是行不通的。但是，这可能与eagle项目或Daplink无关。

It is my problem.now,it is solved,but i have a now problem:the auto reset can not use. 
![无标题](https://user-images.githubusercontent.com/67181123/106404208-0ef3be80-646d-11eb-8431-e893c0c1a96c.png)
