### ISSUE TITLE
Downloading to board

### ISSUE THREAD

**Issue by BibyThm** [ARMmbed/DAPLink#769]
I have edited the DAPLink firmware for STM32F373CC and obtained the following files when compiled as attached. Which of these files should be loaded to the board? What distinguishes these files?
![pic3](https://user-images.githubusercontent.com/77743078/105572969-48973c00-5d80-11eb-8f25-fb5c5aa00783.JPG)

**Comment by 0xc0170** [comment]
The answer is here:  https://github.com/ARMmbed/DAPLink/blob/master/docs/BUILD_OUTPUT.md
