### ISSUE TITLE
Assigning HIC ID 

### ISSUE THREAD

**Issue by BibyThm** [ARMmbed/DAPLink#772]
I am customizing the daplink files for STM32F373CC. How to obtain HIC_ID for STM32F373CC? Can it be customized or should it be given within a specific range?

**Comment by flit** [comment]
Previously the HIC IDs were incremental. This caused problems with multiple people allocating prospective IDs, as you can imagine.

Moving forward, HIC IDs should ideally be composed of 4 ASCII characters related to the HIC's part number. For the LPC55S69 HIC I used 'LPC\x55' (0x4c504355). So for your HIC, something like 'F373' (0x46333733) would be good.
