### ISSUE TITLE
Device Release Number

### ISSUE THREAD

**Issue by Ashleyvk** [ARMmbed/DAPLink#774]
In usb_config.c, for assigning value to USBD_DEVDESC_BCDDEVICE, where do I obtain the device release number from?

**Comment by 0xc0170** [comment]
I would expect if you are porting stm32 device, it would be assigned by stm32 vendor. Do they provide these? See some details as well here https://www.keil.com/pack/doc/mw/USB/html/_u_s_b__device__descriptor.html
