### ISSUE TITLE
stm32 connect with nrf51822 not support for "drag and drop"

### ISSUE THREAD

**Issue by nefusmzj** [ARMmbed/DAPLink#780]
**stm32 connect with nrf51822 not support for "drag and drop"**
- HIC:stm32f103cbt6
- target: nrf52833 
- Interface Version: 0256
- Bootloader Version: 0254
- Enable MSD, CDC, HID, WebUSB

The interface code is compiled with keil5, It work right with WebUsb and CMSIS-DAP Mode，but when  "drag and drop" the same target firmware into the disk in explorer,  the progress bar run right and finish copy right，but the target firmware not work。

Has anyone come across to the same problem?

Thank you!

**Comment by mathias-arm** [comment]
There is no DAPLink project combining `stm32f103xb` HIC and nrf52833 (or nrf51822) target. If you created your own so could you share it? Otherwise it would be a good explanation why it does not work.
