### ISSUE TITLE
[GCC] Build Errors

### ISSUE THREAD

**Issue by Ashleyvk** [ARMmbed/DAPLink#798]
![Post](https://user-images.githubusercontent.com/74317336/113054326-e830da80-91c6-11eb-98ba-21ae62717a4a.JPG)
![Pre](https://user-images.githubusercontent.com/74317336/113054335-ea933480-91c6-11eb-83c1-74be04c30249.JPG)
![version_git](https://user-images.githubusercontent.com/74317336/113054338-ea933480-91c6-11eb-9660-8e9357d964f6.JPG)

While building the project using gcc, we encountered the following errors with pre and post build script. 
version_git.h file is not generated and has to be added manually

**Comment by symovs** [comment]
@flit @mathias-arm Just a note - .bin file generated by GCC compiler is not working. Only the .hex file generated is working. Maybe the .bin file is same as the base file generated for KEIL which should not be used. 

![image](https://user-images.githubusercontent.com/66220236/113274887-cbe28a00-92fb-11eb-8959-c9ecb627960b.png)

**Comment by mbrossard** [comment]
@Ashleyvk: GitHub Actions work with [Windows](https://github.com/mbrossard/DAPLink/actions/workflows/windows.yml). You can look at the logs and GitHub's [windows-2019](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md) configuration to see if you can figure out what is wrong.
@symovs: You should use the `*_if_crc.bin` or `*_if_crc.hex` files. The `*_if.bin` file does not have the CRC computed.

**Comment by mathias-arm** [comment]
Closing all STM32WBxx issues. Use #835 or start a STM32WBxx discussion.
