### ISSUE TITLE
issue of bootloader 0254 or interface 0254?

### ISSUE THREAD

**Issue by victor-chn** [ARMmbed/DAPLink#801]
Hi, I bought a keywish new:bit (but on PCB shows BBS micro:bit), V1.6. one day it cannot start.

I connect the board on PC and swith in maintenance mode. here are the contenu of the original Detail.txt:

# DAPLink Firmware - see https://mbed.com/daplink
Unique ID: 99013601066800363237423143123250a5a5a5a597969908
HIC ID: 97969908
Auto Reset: 1
Automation allowed: 1
Overflow detection: 1
Daplink Mode: Interface
Interface Version: 0254
Bootloader Version: 0254
Git SHA: ce9fa5610f6d447fbc712b6c2215877285435b85
Local Mods: 1
USB Interfaces: MSD, CDC, HID, WebUSB
Bootloader CRC: 0xa00fdafe
Interface CRC: 0x03e7cf12
Remount count: 0
URL: https://microbit.org/device/?id=9901&v=0254

I found the firmware 0254 from Github but when I drag and drop into MAINTENANCE, the load was fail. here is the fail.txt and detail.txt after i load 0254

Fail.txt:
error: In application programming aborted due to an out of bounds address.
type: interface

detail.txt
# DAPLink Firmware - see https://mbed.com/daplink
Unique ID: 00000000066800363237423143123250a5a5a5a597969908
HIC ID: 97969908
Auto Reset: 0
Automation allowed: 1
Overflow detection: 0
Daplink Mode: Bootloader
Bootloader Version: 0254
Git SHA: ce9fa5610f6d447fbc712b6c2215877285435b85
Local Mods: 1
USB Interfaces: MSD
Bootloader CRC: 0xa00fdafe
Interface CRC: 0x4915d882
Remount count: 2
URL: https://mbed.com/daplink

Anyone can help me to understand what's the problem and how to resolve it?

Thanks for your kindly help

**Comment by mathias-arm** [comment]
This a question for Keywish. The information you sent says those files are built from a commit that is not from this repository.
