### ISSUE TITLE
load program failed,uninitialize the target MCU

### ISSUE THREAD

**Issue by Red-oak-tree** [ARMmbed/DAPLink#808]
Mbed Studio: 1.4.0 
KL25Z-ARMC6 
MbedOS:6 
load program failed.

fail.txt 
error: The interface firmware FAILED to uninitialize the target MCU type: target
firmware name：0254_k20dx_frdmkl25z_0x8000.bin

**Comment by mathias-arm** [comment]
I am reading it as you are trying to load the `0254_k20dx_frdmkl25z_0x8000.bin` through Mbed Studio.

You should most likely be using the bootloader procedure (switch to `MAINTENANCE`). Look for the procedure for your board on https://armmbed.github.io/DAPLink/ (additional help to find the button for your board might be in its user manual).

**Comment by Red-oak-tree** [comment]
thank you.I am use "print()" to print dubug message.
