### ISSUE TITLE
Work on JlinkV11 board and connected to the computer but display RDDI-DAP ERROR

### ISSUE THREAD

**Issue by Kevincoooool** [ARMmbed/DAPLink#814]
I compiled the latest firmware, then downloaded the firmware to the Jlink V11 board, connected to the computer and displayed RDDI-DAP ERROR. I knew that some pins of Jlink V11 and LPCLINK were inconsistent, so I also changed the pins, but I found that I changed the pins There is no difference between before and after, both are RDDI-DAP ERROR, I don’t know where the problem is

**Comment by mathias-arm** [comment]
Can you be more clear on what this "Jlink V11 board" is? It would help to know what MCU this is, what DAPLink project configuration you are trying to use and preferably some schematic (or at least a pin-out). Also the nature and content of the RDDI-DAP error would be helpful.
