### ISSUE TITLE
DAPLink Firmware Debugging

### ISSUE THREAD

**Issue by Ashleyvk** [ARMmbed/DAPLink#828]
In order to debug the DAPLink firmware, which tool and ide should be used?

**Comment by asier70** [comment]
I compiled DAPLink for STM32F103 using GCC on eclipse IDE with GNU MCU Eclipse Plug-ins. It is complicated to prepare such project but it works and can be debuged using openocd.

**Comment by Ashleyvk** [comment]
Im having a JLink EDU which communicates with the controller via JTAG.

**Comment by mathias-arm** [comment]
Closing all STM32WBxx issues. Use #835 or start a STM32WBxx discussion.
