### ISSUE TITLE
Data Send Error

### ISSUE THREAD

**Issue by BibyThm** [ARMmbed/DAPLink#843]
Is there any standard procedure for USBD_CDC_ACM_DataSend() ? How much delay is required for a data transmission? Is it calculated based on baud rate? Is it required to clear write buffer in the above function manually? We are planning to send a set of data based on the input value. @mathias-arm @mbrossard @flit @asier70

**Comment by mathias-arm** [comment]
There is no delay involved with the usage of `USBD_CDC_ACM_DataSend()`. DAPLink makes a periodic call to `cdc_process_event()` in `source/daplink/usb2uart/usbd_user_cdc_acm.c`. This function uses `USBD_CDC_ACM_DataFree()` to see how much space is left in the send buffer.

Depending on the activity you might want to increase the size of `USBD_CDC_ACM_SENDBUF_SIZE`.
