### ISSUE TITLE
OpenOCD DAPLink Issue

### ISSUE THREAD

**Issue by Ashleyvk** [ARMmbed/DAPLink#844]
I've downloaded the DAPLink firmware into the STM32WB55RG controller. In openocd, by selecting the interface as CMSIS-DAP, the following error is obtained.
 Error: The specified debug interface was not found (cmsis-dap)
@flit @asier70 @dotnfc @shiva-pandit

**Comment by elfmimi** [comment]
Try openocd 0.11.0 .

**Comment by mathias-arm** [comment]
I guess it's a duplicate of #792
