### ISSUE TITLE
version_git.h generation fails

### ISSUE THREAD

**Issue by gaborcsapo** [ARMmbed/DAPLink#857]
`git describe HEAD` fails with `fatal: No names found, cannot describe anything.` unless there's a tag in the commit history. If this step fails in generate_version_file() from pre_build_script.py, the compilation will fail with error: "vfs_user.c:530:64: error: expected ')' before 'GIT_DESCRIPTION'"

Can we exclude GIT_DESCRIPTION from the DETAILS.txt file? Or can we have a fall back to `git rev-parse --short HEAD` in generate_version_file()?

**Comment by flit** [comment]
Oops! Thanks for letting us know!

**Comment by mathias-arm** [comment]
@gaborcsapo can you check if #858 works for you?

**Comment by gaborcsapo** [comment]
Yes, thank you. It works.
