### ISSUE TITLE
about RTOS2 tick freq question on Develop branch

### ISSUE THREAD

**Issue by wjzhang** [ARMmbed/DAPLink#893]
Hi:  
   why the DAPLink  use  10K frequency for RTOS2 system tick? it's mean 0.1ms.
   or this is bug.  the DAPLink  RTOS2 tick set to 10ms.   the OS_TICK_FREQ   should be 100. 
   what's i misunderstand? 

the Develop branch setting:
#define OS_TICK_FREQ                10000 // DAPLINK. Default was: 1000
const osRtxConfig_t osRtxConfig \
__USED \
__attribute__((section(".rodata"))) =
{
  //lint -e{835} "Zero argument to operator"
  0U   // Flags
#if (OS_PRIVILEGE_MODE != 0)
  | osRtxConfigPrivilegedMode
#endif
#if (OS_STACK_CHECK != 0)
  | osRtxConfigStackCheck
#endif
#if (OS_STACK_WATERMARK != 0)
  | osRtxConfigStackWatermark
#endif
  ,
  (uint32_t)OS_TICK_FREQ,
#if (OS_ROBIN_ENABLE != 0)
  (uint32_t)OS_ROBIN_TIMEOUT,
#else
  0U,
#endif
.....
  // Setup SVC and PendSV System Service Calls
  SVC_Setup();

  // Setup RTOS Tick
  if (OS_Tick_Setup(osRtxConfig.tick_freq, OS_TICK_HANDLER) != 0) {
    EvrRtxKernelError((int32_t)osError);
    //lint -e{904} "Return statement before end of function" [MISRA Note 1]
    return osError;
  }

**Comment by mathias-arm** [comment]
With a little bit more context in `source/rtos2/Include/RTX_Config.h`:
```
#ifndef OS_TICK_FREQ
#define OS_TICK_FREQ                10000 // DAPLINK. Default was: 1000
#endif
```

The value is set to `100` through compiler command line:
```
$ grep -r OS_TICK_FREQ records
records/rtos/rtos-cm0.yaml:        - OS_TICK_FREQ=100
records/rtos/rtos-cm33.yaml:        - OS_TICK_FREQ=100
records/rtos/rtos-cm4.yaml:        - OS_TICK_FREQ=100
records/rtos/rtos-cm3.yaml:        - OS_TICK_FREQ=100
```

We should probably revert to default value in `RTX_Config.h` and remove comment because this value is ignored.
