### ISSUE TITLE
Debug mode compilation

### ISSUE THREAD

**Issue by BibyThm** [ARMmbed/DAPLink#894]
While trying to debug the target device using pyocd, we encountered the following issue.
https://github.com/pyocd/pyOCD/issues/1222

Inorder to rectify it, we would like to compile the DAPLink firmware in debug mode in gcc. How can it be done? 
@flit @mathias-arm

**Comment by mathias-arm** [comment]
DAPLink is compiled by default with debug informations for all compilers ([see in  gcc_arm.yaml](https://github.com/ARMmbed/DAPLink/blob/2024a091d958f21e2238ea8ed5fadeccd238e484/records/tools/gcc_arm.yaml#L15)).

Looking at https://github.com/pyocd/pyOCD/issues/1222, it seems some of the things you should look at are [Board-IDs](https://github.com/ARMmbed/DAPLink/wiki/Board-IDs), [PORT_BOARD.md](https://github.com/ARMmbed/DAPLink/blob/main/docs/PORT_BOARD.md) and the [board-handling code in pyocd](https://github.com/pyocd/pyOCD/tree/main/pyocd/board).

As mentioned in #798, please use your PR #835 or start *one* discussion to discuss your HIC development issues.
