### ISSUE TITLE
Very slow serial data transfer via WebUSB (< 9600 baud)

### ISSUE THREAD

**Issue by ccattuto** [ARMmbed/DAPLink#900]
Hello,

I'm testing the "daplink-serial" example of dapjs (WebUSB serial, https://armmbed.github.io/dapjs/examples/daplink-serial/web.html). I'm using a NRF52-DK board with the DAPLink firmware"0254_sam3u2c_mkit_dk_dongle_nrf5x_0x5000.bin" (from https://daplink.io/) installed on the SAM MCU. Flashing firmware via WebUSB, drag & drop and everything else works just fine.

The test application running on the nRF52 pushes data to the UART at 115200 baud, with hardware flow control enabled. This has been confirmed to work at the correct speed, without data loss, using the USB CDC serial interface provided by DAPLink to the host computer. This also works correctly with other virtual COM port implementations (i.e., the one provided by the J-Link MCU firmware).

ISSUE: the DAPLink WebUSB serial receives data at a very low baud rate (9600 or lower) despite the baud rate being set to 115200 via dap.js ( target.setSerialBaudrate(115200) ). This is in contrast with the correct speed being observed when using the DAPLink USB CDC interface, so it looks like a WebUSB issue. No data loss is observed when hardware flow control is enabled on the nRF52 side. On disabling hardware flow control, data loss is observed via WebUSB on the host (and the string "DAPJLink:Overflow" appears in the stream) but no data loss occurs via DAPLink USB CDC. It looks like there is some bottleneck affecting WebUSB serial transfers.

Thanks!

**Comment by ccattuto** [comment]
The WebUSB bottleneck is in DAP.js: it is the polling frequency of the serial, which by default is set to 10Hz (100ms delay) limiting the bandwidth to ~640 bytes / s (assuming a maximum payload size of 64 bytes). Increasing the polling frequency proportionally makes available more bandwidth (e.g., by setting a 5ms delay with startSerialRead(serialDelay=5) one gets enough link bandwidth to support serial data transfer at 115200 baud.

**Comment by mathias-arm** [comment]
Thank you for the update.
