### ISSUE TITLE
0xE00ABE00, 0x062D780D, 0x24084068, 0xD3000040, 0x1E644058, 0x1C49D1FA, 0x2A001E52, 0x4770D1F2

### ISSUE THREAD

**Issue by yzhengBTT** [ARMmbed/DAPLink#902]
Hello, I am not quite clear about this section of code, looking forward to your reply.

0xE00ABE00, 0x062D780D, 0x24084068, 0xD3000040, 0x1E644058, 0x1C49D1FA, 0x2A001E52, 0x4770D1F2

**Comment by elfmimi** [comment]
You can do:
`python3 -c '__import__("sys").stdout.buffer.write(__import__("struct").pack("8I", 0xE00ABE00, 0x062D780D, 0x24084068, 0xD3000040, 0x1E644058, 0x1C49D1FA, 0x2A001E52, 0x4770D1F2))' > algo.bin`
and then
`arm-none-eabi-objdump -b binary -m arm -M force-thumb -D algo.bin`

**Comment by elfmimi** [comment]
This has been led to a resolution in other place.  https://github.com/pyocd/pyOCD/discussions/1252

so the issue can be closed.

**Comment by mbrossard** [comment]
Thanks @elfmimi
