### ISSUE TITLE
Cannot build source without a git repo

### ISSUE THREAD

**Issue by c1728p9** [ARMmbed/DAPLink#95]
DAPLink cannot be built without having a valid git repo.

**Comment by Josephc3** [comment]
if you install Git and Git desktop, and then clone the repository to your computer, it can then be built.

**Comment by c1728p9** [comment]
That is the typical use case and that use case still works.  I'm talking about the case where it is just source and no version control is present.

**Comment by cederom** [comment]
i would just treat that as build dependency..?

**Comment by brianesquilona** [comment]
Version file isneeded.
