### ISSUE TITLE
How to generate pure Bootloader project?

### ISSUE THREAD

**Issue by arilink** [ARMmbed/DAPLink#953]
I know that the Bootloader of DAP Link is very easy to use. I would like to ask how to generate a pure Bootloader project？

**Comment by gaborcsapo** [comment]
Do you mean how to build a bootloader? 

You can probably take a look at the [Dev guid](https://github.com/ARMmbed/DAPLink/blob/main/docs/DEVELOPERS-GUIDE.md) and just select a bootloader target such as stm32f103xb_bl. THe _bl at the end of the target suggests bootloader.
