### ISSUE TITLE
Can't connect to the target chip

### ISSUE THREAD

**Issue by PENGCHUMING** [ARMmbed/DAPLink#961]
### Discussed in https://github.com/ARMmbed/DAPLink/discussions/960

<div type='discussions-op-text'>

<sup>Originally posted by **PENGCHUMING** May 16, 2022</sup>
Hello,

I find that when I connect the 22Ω resistor in the output port of SWDIO and SWDCLK, I cannot connect the CHIP of ARM® Cortex® -M4, such as STM32F4, but I can connect it by changing it to 100Ω. I don't know why  </div>

**Comment by sdyncyang** [comment]
i have same question about this , but the link can not avaliable now ,could some one help to explan this issue?
thanks.
