### ISSUE TITLE
What is the default crystal frequency 

### ISSUE THREAD

**Issue by bihailantian655** [ARMmbed/DAPLink#965]
Which one is the file for the custom crystal frequency configuration

What is the default crystal frequency of the external crystal of stm32

**Comment by mathias-arm** [comment]
For `stm32f103xb` it's 8 MHz (see [here](https://github.com/ARMmbed/DAPLink/blob/1c60ddb5a2b9203c7d44ac089ac5772b9e9e6d31/source/hic_hal/stm32/stm32f103xb/cmsis/system_stm32f1xx.c#L96) and [here](https://github.com/ARMmbed/DAPLink/blob/1c60ddb5a2b9203c7d44ac089ac5772b9e9e6d31/source/hic_hal/stm32/stm32f103xb/STM32F1xx_HAL_Driver/stm32f1xx_hal_conf.h#L97))
