### ISSUE TITLE
The STM32F103xb_if projects Tag v0257 and after could not be recognized in MDK

### ISSUE THREAD

**Issue by xiaohanhan1982** [ARMmbed/DAPLink#977]
The STM32F103xb_if projects Tag v0257 and after could not be recognized in MDK, the Tag v0254 is OK. 
The device 'CMSIS-DAP v2' can be find in Device manager(Windows 10), but could not be recognized in MDK.
Anybody has solutions？

**Comment by mbrossard** [comment]
@zjli-2019 [reported](https://github.com/ARMmbed/DAPLink/pull/805#issuecomment-1041151569) that changing `CMSIS_DAP_PRODUCT_NAME` to `"CMSIS-DAP"` solved the issue. Could you test that and report?

**Comment by penjun71** [comment]
i use lpc11u35,same problem.
i edit this ,fix this problem!
dap_strings.h
#define CMSIS_DAP_PRODUCT_NAME "DAPLink CMSIS-DAP"

**Comment by sdyncyang** [comment]
i met same issue , STM32F103xb_if projects seems worked, due to i can find the CMSIS-DAP v2 and WebUSB: CMSIS-DAP in compture hardware list , but can not find in MDK , i changed CMSIS_DAP_PRODUCT_NAME to "CMSIS-DAP" ,but still not work ...
