### ISSUE TITLE
Problem with microbitv2 and DAPlink v0257

### ISSUE THREAD

**Issue by stm32wrobotyce** [ARMmbed/DAPLink#997]
Hi, 
I am writing Host software for STM32G0 that communicates with micro:bit v2. So far I had micro:bit v2.00 boards and communication through CDC device worked fine for me. However, after v2.20 and v2.21, there was a problem with activating the USB device (the LED responsible for USB does not light up). The same problem appeared on micro:bit v2.00 boards after upgrading to v0258 (beta), so I think it is related to changes in DAPLink v0257.
So far, on the HOST USB side on STM32G0, the procedure was as follows: after detecting the device, I waited 200 ms, reset the port. Then I waited for the port to turn on and read the speed. I set the pipe in and out for Control Endpoint. I then read the Device Descriptor, set the address and read the Configuration and Interface Descriptiors. These all read correctly as v2.00 as v2.20/2.21 (v0257 DAPLink). In the next step, I send the DAPLink Set Configuration Request with a value of "1". This is the default HOST USB procedure in the library from ST. 
And at this point so far the USB Activity LED turns on. However, in newer versions, it does not turn on and I am not able to establish communication before the CDC. Does the newer software (v0257 DAPLink) require any additional configuration? Am I doing something wrong? I have looked through the change code, but I am unable to find the difference that causes this error. Of course, when connected to the computer, everything works ok. The problem is on my host side on the STM32.
Can anyone help me find the difference between these version of DAPLink in USB Device Configuration procedure?

**Comment by mathias-arm** [comment]
I am guessing you are installing the binaries from: https://tech.microbit.org/software/daplink-interface/

Is the following summary of your test correct?

- v2.00 with 0255: ✅ 
- v2.00 with 0258-beta1: ❌
- v2.20 with 0256: ❓
- v2.20 with 0257: ❌
- v2.21 with 0257: ❌

**Comment by stm32wrobotyce** [comment]
Hi,   Thanks for Your answer.   Exactly, I tried all of this binaries and test results are as you makred. I suspect, that is connected maybe with some flags or features but I can&#39;t find which one of USB Request I need to send to activate correctly USB.   Best Regards,  Piotr Czaplicki  
            
          
     
      
       
        Dnia 4 stycznia 2023 20:57 Mathias Brossard ***@***.***&gt; napisał(a):
       
    
       
         
 I am guessing you are installing the binaries from:  tech.microbit.org https://tech.microbit.org/software/daplink-interface/ 
 Is the following summary of your test correct? 
 
 v2.00 with 0255:  ✅ 
 v2.00 with 0258-beta1:  ❌ 
 v2.20 with 0256:  ❓ 
 v2.20 with 0257:  ❌ 
 v2.21 with 0257:  ❌
