### ISSUE TITLE
why using SWDIO_IN_PIN and SWDIO_OUT_PIN for STM32F103

### ISSUE THREAD

**Issue by sdyncyang** [ARMmbed/DAPLink#998]
Hi 
I am confusing on using SWDIO_IN_PIN and SWDIO_OUT_PIN two pins with 100ohm for STM32F103CB, and find the signal is always keeps high, the DAP connect in keil is failed ...could some one give the help on this issue ? thanks

**Comment by mathias-arm** [comment]
The point of having separate `SWDIO_IN_PIN` and `SWDIO_OUT_PIN` pins is to avoid reconfiguring the GPIO pin from output to input in the middle of the SWD transactions. If I remember correctly `SWDIO` should be high most of time. Do you see `SWCLK` changing but `SWDIO` never does?
